name: fresh_picked
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  flutter_screenutil: ^5.9.3
  pinput: ^5.0.1
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  fluttertoast: ^8.2.12
  connectivity_plus: ^6.1.3
  get: ^4.7.2
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  app_settings: ^5.2.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  shimmer: ^3.0.0
  google_maps_flutter: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

dependency_overrides:
  dio: ^5.8.0+1  # Ensure the same version as specified above to avoid conflict
  get: ^4.7.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Abhaya Libre
      fonts:
        - asset: assets/fonts/AbhayaLibre-Bold.ttf
          weight: 700
        - asset: assets/fonts/AbhayaLibre-Medium.ttf
          weight: 800
        - asset: assets/fonts/AbhayaLibre-SemiBold.ttf
          weight: 600

    - family: Inter
      fonts:
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
